#ifndef __J_CALLBACK_H__
#define __J_CALLBACK_H__

enum {
  CALLBACK_POLL,
  CALLBACK_EVENT_PROCESS_ONLINE,
  CALLBACK_EVENT_PROCESS_OFFLINE,
  CALLBACK_EVENT_STREAM_BEGIN,
  CALLBACK_EVENT_STREAM_END,
  CALLBACK_EVENT_SPEECH_READY,
  CALLBACK_EVENT_SPEECH_START,
  CALLBACK_EVENT_SPEECH_STOP,
  CALLBACK_EVENT_RECOGNITION_BEGIN,
  CALLBACK_EVENT_RECOGNITION_END,
  CALLBACK_EVENT_SEGMENT_BEGIN,
  CALLBACK_EVENT_SEGMENT_END,
  CALLBACK_EVENT_PASS1_BEGIN,
  CALLBACK_EVENT_PASS1_FRAME,
  CALLBACK_EVENT_PASS1_END,
  CALLBACK_RESULT_PASS1_DETERMINED,
  CALLBACK_RESULT_PASS1_INTERIM,
  CALLBACK_RESULT_PASS1,
  CALLBACK_RESULT_PASS1_GRAPH,
  CALLBACK_STATUS_PARAM,
  CALLBACK_EVENT_PASS2_BEGIN,
  CALLBACK_EVENT_PASS2_END,
  CALLBACK_RESULT,
  CALLBACK_RESULT_GMM,
  CALLBACK_RESULT_GRAPH,
  CALLBACK_RESULT_CONFNET,

  CALLBACK_ADIN_CAPTURED,
  CALLBACK_ADIN_TRIGGERED,

  CALLBACK_EVENT_PAUSE,
  CALLBACK_EVENT_RESUME,
  CALLBACK_PAUSE_FUNCTION,

  CALLBACK_EVENT_GRAMMAR_UPDATE,

  CALLBACK_DEBUG_PASS2_POP,
  CALLBACK_DEBUG_PASS2_PUSH,

  SIZEOF_CALLBACK_ID
};

#define MAX_CALLBACK_HOOK 10

#endif /* __J_CALLBACK_H__ */
